import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/views/**/*.blade.php',
        './resources/js/**/*.js',
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'primary-fixed': '#dce1ff',
                'primary-fixed-dim': '#b6c4ff',
                'on-primary-fixed': '#00164e',
                'on-primary-fixed-variant': '#264191',
                'primary': '#00236f',
                'on-primary': '#ffffff',
                'primary-container': '#1e3a8a',
                'on-primary-container': '#90a8ff',
                'secondary': '#9d4300',
                'on-secondary': '#ffffff',
                'secondary-container': '#fd761a',
                'on-secondary-container': '#5c2400',
                'secondary-fixed': '#ffdbca',
                'secondary-fixed-dim': '#ffb690',
                'on-secondary-fixed': '#341100',
                'on-secondary-fixed-variant': '#783200',
                'tertiary': '#4b1c00',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#6e2c00',
                'on-tertiary-container': '#f39461',
                'tertiary-fixed': '#ffdbcb',
                'tertiary-fixed-dim': '#ffb691',
                'on-tertiary-fixed': '#341100',
                'on-tertiary-fixed-variant': '#773205',
                'error': '#ba1a1a',
                'on-error': '#ffffff',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                'surface': '#f8f9ff',
                'surface-dim': '#cbdbf5',
                'surface-bright': '#f8f9ff',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#eff4ff',
                'surface-container': '#e5eeff',
                'surface-container-high': '#dce9ff',
                'surface-container-highest': '#d3e4fe',
                'surface-variant': '#d3e4fe',
                'surface-tint': '#4059aa',
                'on-surface': '#0b1c30',
                'on-surface-variant': '#444651',
                'inverse-surface': '#213145',
                'inverse-on-surface': '#eaf1ff',
                'inverse-primary': '#b6c4ff',
                'outline': '#757682',
                'outline-variant': '#c5c5d3',
                'background': '#f8f9ff',
                'on-background': '#0b1c30',
            },
            borderRadius: {
                sm: '0.25rem',
                DEFAULT: '0.5rem',
                lg: '0.5rem',
                xl: '0.75rem',
                '2xl': '1rem',
                '3xl': '1.5rem',
                full: '9999px',
            },
            spacing: {
                xs: '4px',
                base: '8px',
                sm: '12px',
                gutter: '24px',
                md: '24px',
                'margin-mobile': '16px',
                'margin-desktop': '40px',
                lg: '48px',
                xl: '80px',
            },
            fontFamily: {
                body: ['Inter', 'system-ui', 'sans-serif'],
                'body-md': ['Inter', 'system-ui', 'sans-serif'],
                'body-lg': ['Inter', 'system-ui', 'sans-serif'],
                'label-sm': ['Inter', 'system-ui', 'sans-serif'],
                'label-caps': ['JetBrains Mono', 'monospace'],
                'headline-lg': ['Inter', 'system-ui', 'sans-serif'],
                'headline-lg-mobile': ['Inter', 'system-ui', 'sans-serif'],
                'headline-md': ['Inter', 'system-ui', 'sans-serif'],
            },
            fontSize: {
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'label-sm': ['14px', { lineHeight: '20px', fontWeight: '500' }],
                'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'headline-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
            },
            boxShadow: {
                'lift': '0px 4px 12px rgba(30, 41, 59, 0.08)',
            },
            maxWidth: {
                '7xl': '1280px',
            },
        },
    },
    plugins: [
        forms,
    ],
};
